version: '3.4'

services:
  brook.cnblogimage.core:
    image: gaozengzhi/brook-cnblog-core
    ports:
      - "32769:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_CNBLOG_BLOGID=xxx
      - ASPNETCORE_CNBLOG_USERNAME=xxx
      - ASPNETCORE_CNBLOG_PASSWORD=xxx
      - ASPNETCORE_TOKEN=xxxx
      - VIRTUAL_HOST=xxx.xxx.cn
    restart: always 
    volumes:
      - ./Resources:/app/Resources

networks:
   default:
     external:
       name: nginx-proxy